#开发环境
server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       hibernate.use-new-id-generator-mappings: true
       hibernate.cache.use_second_level_cache: false
       hibernate.cache.use_query_cache: false
       hibernate.cache.use_minimal_puts: true
       hibernate.generate_statistics: false





